// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqN0EgMV_raSTDyL9Op7MqU8mUOFOIxMI',
    appId: '1:615321182633:web:7ae293a4cad617905824b8',
    messagingSenderId: '615321182633',
    projectId: 'recipeapp-dfc59',
    authDomain: 'recipeapp-dfc59.firebaseapp.com',
    storageBucket: 'recipeapp-dfc59.appspot.com',
    measurementId: 'G-N1HB2JJ34B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz6ta8DRAhHRXdgx9RqXfIfLjIDqErUeM',
    appId: '1:615321182633:android:3eeba90c03c7ecfc5824b8',
    messagingSenderId: '615321182633',
    projectId: 'recipeapp-dfc59',
    storageBucket: 'recipeapp-dfc59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxNOiWpr4udddCQCKBvJ4sT8f-2YaAskQ',
    appId: '1:615321182633:ios:2b77834a8bd241ca5824b8',
    messagingSenderId: '615321182633',
    projectId: 'recipeapp-dfc59',
    storageBucket: 'recipeapp-dfc59.appspot.com',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxNOiWpr4udddCQCKBvJ4sT8f-2YaAskQ',
    appId: '1:615321182633:ios:2b77834a8bd241ca5824b8',
    messagingSenderId: '615321182633',
    projectId: 'recipeapp-dfc59',
    storageBucket: 'recipeapp-dfc59.appspot.com',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqN0EgMV_raSTDyL9Op7MqU8mUOFOIxMI',
    appId: '1:615321182633:web:05d6633b818f25d45824b8',
    messagingSenderId: '615321182633',
    projectId: 'recipeapp-dfc59',
    authDomain: 'recipeapp-dfc59.firebaseapp.com',
    storageBucket: 'recipeapp-dfc59.appspot.com',
    measurementId: 'G-N3WWGKEVP4',
  );
}
